import { Prisma } from "@prisma/client";

export const companySelect: Prisma.CompanySelect = {
  id: true,
  name: true,
  email: true,
  phoneCountryCode: true,
  phone: true,
  csdNumber: true,
  symbol: true,
  description: true,
  sector: true,
  country: true,
  city: true,
  documents: true,
  sharePrice: true,
  totalShares: true,
  availableShares: true,
  marketCap: true,
  closingPrice: true,
  previousClosingPrice: true,
  priceChange: true,
  tradedVolume: true,
  tradedValue: true,
  snapshotDate: true,
  contract: true,
  isVerified: true,
  createdById: true,
  createdAt: true,
  updatedAt: true,
};
